version: '3.8'

services: 
  web: 
    entrypoint: php websocket.php
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket
    ports:
      - "8000:8000"
    volumes: 
      - .:/opt/www
    networks:
      - default
